tasks:
    hello:
        name: Hello World
        command: |
            npm run dev
        triggeredBy:
        - manual
        # - postEnvironmentStart
        # - postDevcontainerStart

services:
    backend:
        name: Backend Service
        description: Example service simulating a backend
        commands:
            start: |
                npm run dev
            ready: |
                if [ -f /tmp/backend.started ]; then
                    echo "Backend service is ready"
                    exit 0
                else
                    echo "Backend service is not ready"
                    exit 1
                fi
            # stop: |
            # 	echo "Stopping backend service..."
            # 	rm /tmp/backend.started
            #   pkill backend
        triggeredBy:
            - postEnvironmentStart
            # - postDevcontainerStart
