tasks:
    setup:
        name: Initial Setup
        command: |
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            echo "Installing dependencies..."
            npm install
            echo "Building TypeScript code..."
            npm run build
        triggeredBy:
            - postEnvironmentStart

    start-dev:
        name: Start Development Server
        command: |
            echo "Starting development server..."
            npm run dev
        triggeredBy:
            - manual

services:
    node-server:
        name: Node.js Server
        description: Backend Node.js server for the application
        commands:
            start: |
                echo "Starting the Node.js server..."
                npm run dev &
                touch /tmp/node-server.started
            ready: |
                if [ -f /tmp/node-server.started ]; then
                echo "Node.js server is ready"
                exit 0
                else
                echo "Node.js server is not ready"
                exit 1
                fi
        triggeredBy:
            - postEnvironmentStart
